# Generated by Django 3.0.2 on 2020-01-21 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classement', '0003_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='max_student',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='student',
            name='school_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classement.School'),
        ),
    ]
